on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        devtool: ["y", "n"]
    name: build-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: "2.9.9"

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --devtool=${{ matrix.devtool }}

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}-${{ github.sha }}
          path: |
            bin/

  update-release-notes:
    outputs:
      release_notes: ${{ steps.extract-release-notes.outputs.release_notes }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: |-
            ${{ steps.extract-release-notes.outputs.release_notes }}

            | File | SHA256 |
            | ---- | ------ |

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        devtool: ["y", "n"]
    env:
      FinalName: ${{ github.event.repository.name }}-windows-x64-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}
      ArtifactName: ${{ github.event.repository.name }}-windows-x64-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}-${{ github.sha }}
    name: upload-to-release-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}
    steps:
      - run: |
          echo "FinalName: ${{ env.FinalName }}"
          echo "ArtifactName: ${{ env.ArtifactName }}"

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ArtifactName }}
          path: artifact

      - run: |
          cp CHANGELOG.md README.md LICENSE artifact/

      - run: |
          zip -r ../${{ env.FinalName }}.zip *
        working-directory: artifact

      - id: calculate-sha256-core
        run: |
          echo sha256=$(sha256sum ${{ env.FinalName }}.zip | awk '{print $1}') >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |-
            | ${{ env.FinalName }}.zip | ${{ steps.calculate-sha256-core.outputs.sha256 }} |
          files: |
            ${{ env.FinalName }}.zip
